---
region: 'eu-west-2'
availability_zones:
  - "eu-west-2a"
  - "eu-west-2b"

component: 'test'

tags:
  ImportantTag: "important-value"

work_directory: 'build'
configuration_directory: "%{hiera('work_directory')}/%{hiera('source_directory')}"

vpc_cidr: "10.1.0.0/16"

private_zone_vpc_id: 'vpc-a938ffc0'

custom_ami_id: "ami-3fb6bc5b"

cluster_name: 'test-cluster'
cluster_instance_ssh_public_key_path: "%{hiera('project_directory')}/config/secrets/cluster/ssh.public"
cluster_instance_type: 't2.medium'
cluster_instance_amis:
  eu-west-2: "''"
cluster_instance_root_block_device_size: 40

cluster_minimum_size: 1
cluster_maximum_size: 3
cluster_desired_capacity: 2

security_groups: []

include_default_ingress_rule: "yes"
include_default_egress_rule: "yes"

allowed_cidrs:
  - '10.1.0.0/16'
egress_cidrs:
  - '10.1.0.0/16'

enable_container_insights: "no"

protect_cluster_instances_from_scale_in: "no"

include_asg_capacity_provider: "no"
asg_capacity_provider_manage_termination_protection: "no"
asg_capacity_provider_manage_scaling: "no"
asg_capacity_provider_minimum_scaling_step_size: 1
asg_capacity_provider_maximum_scaling_step_size: 1000
asg_capacity_provider_target_capacity: 100
